from __future__ import annotations

import sys
from pathlib import Path


SCHEMAS = {
    "leaf-module": [
        "叶子模块概述", "职责与边界", "领域定位与设计约束", "系统交互与接口关系",
        "核心任务流程", "状态、事件与时序", "核心实现", "配置、宏与运行变体",
        "调试与故障定位", "Agent 开发导航", "证据、限制与待确认项",
    ],
    "module-summary": [
        "层级定位", "子模块组成", "聚合职责与边界", "跨子模块协作", "业务流程汇聚",
        "公共数据与接口", "状态、时序与资源约束", "开发影响导航", "子文档导航", "汇聚证据与限制",
    ],
    "architecture": [
        "系统目标与边界", "总体模块分层", "模块职责", "模块依赖", "跨模块接口",
        "核心数据流", "核心调用流程", "状态与时序关系", "构建配置与运行变体", "架构风险与证据限制",
    ],
    "readme": [
        "项目简介", "代码版本与分析范围", "系统组成", "模块导航", "核心任务流程导航",
        "数据结构与 API 导航", "推荐阅读顺序", "证据说明", "已知覆盖限制",
    ],
    "data-structures": [
        "范围与索引", "核心结构体", "枚举与类型别名", "初始化与生命周期",
        "读写与传递关系", "配置与消息映射", "证据与待确认字段",
    ],
    "call-flows": [
        "流程索引", "触发条件与前置状态", "确定调用链", "数据与配置传播",
        "分支与失败路径", "时序与并发关系", "候选调用与未解析关系", "源码证据与覆盖限制",
    ],
    "api-reference": [
        "API 索引", "函数签名与位置", "参数与返回值", "调用者与被调用者",
        "副作用与状态要求", "错误处理", "配置与条件编译", "证据与限制",
    ],
}


def main() -> int:
    args = sys.argv[1:]
    context = ""
    if "--file" in args:
        context = Path(args[args.index("--file") + 1]).read_text(encoding="utf-8", errors="replace")
    document_type = next((name for name in SCHEMAS if f"文档类型：{name}" in context), "architecture")
    title = next((line.split("：", 1)[1].strip() for line in context.splitlines() if line.startswith("- 文档标题：")), "ClangWiki simulation")
    print(f"# {title}")
    for heading in SCHEMAS[document_type]:
        print(f"\n## {heading}\n\n[simulation] This section is generated by the local fake OpenCode launcher.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
